wip
Signed-off-by: Christopher Maier <cmaier@chef.io>

diff --git a/components/plan-build/hab-plan-build b/components/plan-build/hab-plan-build
--- a/components/plan-build/hab-plan-build
+++ b/components/plan-build/hab-plan-build
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/hab/pkgs/core/bash/4.3.42/20170513213519/bin/bash
 #
 # # Usage
 #
@@ -341,7 +341,7 @@ fi
 # The short version of the program name which is used in logging output
 _program=$(basename "$0")
 # The current version of this program
-HAB_PLAN_BUILD=0.0.1
+HAB_PLAN_BUILD=0.29.0-dev/20170811183449
 # The root path of the Habitat file system. If the `$HAB_ROOT_PATH` environment
 # variable is set, this value is overridden, otherwise it is set to its default
 : ${HAB_ROOT_PATH:=/hab}
@@ -2062,35 +2062,6 @@ _resolve_dependencies() {
   _validate_deps
 }
 
-# **Internal** This writes out a pre_build.env file, similar to the last_build.env
-# that gets written at the end of a build. The purpose of pre_build.env is to provide
-# metadata about what package we're trying to build before we build it. This is useful
-# if the build fails, because a worker can read that file in and use it to report back
-# about what exactly failed.
-_write_pre_build_file() {
-  local plan_owner
-  plan_owner="$(stat -c '%u:%g' "$PLAN_CONTEXT/plan.sh")"
-  pre_build_file="$pkg_output_path/pre_build.env"
-
-  build_line "Writing pre_build file"
-
-  mkdir -pv "$pkg_output_path"
-
-  if [ -f "$pre_build_file" ]; then
-    rm "$pre_build_file"
-  fi
-
-  cat <<-EOF > "$pre_build_file"
-pkg_origin=$pkg_origin
-pkg_name=$pkg_name
-pkg_version=$pkg_version
-pkg_release=$pkg_release
-pkg_ident=${pkg_origin}/${pkg_name}/${pkg_version}/${pkg_release}
-EOF
-
-  chown "$plan_owner" "$pre_build_file" || true
-}
-
 # **Internal**  Build `$PATH` containing each path in our own
 # `${pkg_bin_dirs[@]}` array, and then any dependency's `PATH` entry (direct
 # or transitive) if one exists. The ordering of the path is specific to
@@ -2963,12 +2934,6 @@ _prepare_build_outputs() {
   cp -v "$pkg_artifact" "$pkg_output_path"/
   chown "$plan_owner" "$pkg_output_path/$(basename "$pkg_artifact")" || true
 
-  # At this point, we know it built successfully, so delete the pre_build file
-  pre_build_file="$pkg_output_path/pre_build.env"
-  if [ -f "$pre_build_file" ]; then
-    rm "$pre_build_file"
-  fi
-
   cat <<-EOF > "$pkg_output_path"/last_build.env
 pkg_origin=$pkg_origin
 pkg_name=$pkg_name
@@ -2994,257 +2959,259 @@ do_default_end() {
   return 0
 }
 
-# # Main Flow
+# Main Flow
+# This only runs if we're actually executing the script, rather than
+# sourcing it as a library.
+if [ "${BASH_SOURCE}" == "$0" ]
+then
+    # Parse depot flag (-u)
+    OPTIND=2
+    while getopts "u:" opt; do
+        case "${opt}" in
+            u)
+                HAB_DEPOT_URL=$OPTARG
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG" >&2
+                exit 1
+                ;;
+            :)
+                echo "Option -$OPTARG requires an argument." >&2
+                exit 1
+                ;;
+        esac
+    done
 
-# Parse depot flag (-u)
-OPTIND=2
-while getopts "u:" opt; do
-  case "${opt}" in
-    u)
-      HAB_DEPOT_URL=$OPTARG
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-      ;;
-  esac
-done
+    # Expand the context path to an absolute path
+    PLAN_CONTEXT="$(abspath "$PLAN_CONTEXT")"
+    # Set the initial source root to be the same as the Plan context directory.
+    # This assumes that your application source is local and your Plan exists with
+    # your code.
+    SRC_PATH="$PLAN_CONTEXT"
+    # Expand the path of this program to an absolute path
+    THIS_PROGRAM=$(abspath "$0")
 
-# Expand the context path to an absolute path
-PLAN_CONTEXT="$(abspath "$PLAN_CONTEXT")"
-# Set the initial source root to be the same as the Plan context directory.
-# This assumes that your application source is local and your Plan exists with
-# your code.
-SRC_PATH="$PLAN_CONTEXT"
-# Expand the path of this program to an absolute path
-THIS_PROGRAM=$(abspath "$0")
+    # Now to ensure a `plan.sh` exists where we expect it. There are 2 possible
+    # candidate locations relative to the `$PLAN_CONTEXT` directory: a `./plan.sh`
+    # or a `./habitat/plan.sh`. Only one or the other location is allowed so that
+    # a Plan author isn't confused if they edit one to have this program read
+    # the other.
 
-# Now to ensure a `plan.sh` exists where we expect it. There are 2 possible
-# candidate locations relative to the `$PLAN_CONTEXT` directory: a `./plan.sh`
-# or a `./habitat/plan.sh`. Only one or the other location is allowed so that
-# a Plan author isn't confused if they edit one to have this program read
-# the other.
+    # We'll make sure that both are not present, and if so abort.
+    if [[ -f "$PLAN_CONTEXT/plan.sh" && -f "$PLAN_CONTEXT/habitat/plan.sh" ]];then
+        places="$PLAN_CONTEXT/plan.sh and $PLAN_CONTEXT/habitat/plan.sh"
+        exit_with "A Plan file was found at $places. Only one is allowed at a time" 42
+    fi
+    # We check if the provided path has a `plan.sh` in it in either location. If
+    # not, we'll quickly bail.
+    if [[ ! -f "$PLAN_CONTEXT/plan.sh" ]]; then
+        if [[ -f "$PLAN_CONTEXT/habitat/plan.sh" ]]; then
+            # As the `plan.sh` is in a deeper subdirectory, we'll update the
+            # `$PLAN_CONTEXT` directory to be relative to the actual `plan.sh` file.
+            PLAN_CONTEXT="$PLAN_CONTEXT/habitat"
+        else
+            places="$PLAN_CONTEXT/plan.sh or $PLAN_CONTEXT/habitat/plan.sh"
+            exit_with "Plan file not found at $places" 42
+        fi
+    fi
 
-# We'll make sure that both are not present, and if so abort.
-if [[ -f "$PLAN_CONTEXT/plan.sh" && -f "$PLAN_CONTEXT/habitat/plan.sh" ]];then
-  places="$PLAN_CONTEXT/plan.sh and $PLAN_CONTEXT/habitat/plan.sh"
-  exit_with "A Plan file was found at $places. Only one is allowed at a time" 42
+    # Change into the `$PLAN_CONTEXT` directory for proper resolution of relative
+    # paths in `plan.sh`
+    cd "$PLAN_CONTEXT"
+
+    # Load the Plan
+    build_line "Loading $PLAN_CONTEXT/plan.sh"
+    if source "$PLAN_CONTEXT/plan.sh"; then
+        build_line "Plan loaded"
+    else
+        ret=$?
+        exit_with "Failed to load Plan" $ret
+    fi
+
+    if [[ -n "$HAB_ORIGIN" ]]; then
+        pkg_origin="$HAB_ORIGIN"
+    fi
+
+    # Validate metadata
+    build_line "Validating plan metadata"
+
+    # Test for all required metadata keys
+    required_variables=(
+        pkg_name
+        pkg_origin
+    )
+    for var in "${required_variables[@]}"
+    do
+        if [[ -z "${!var}" ]] ; then
+            exit_with "Failed to build. '${var}' must be set." 1
+        fi
+    done
+
+    # Test to ensure package name contains only valid characters
+    for var in pkg_name pkg_origin; do
+        if [[ ! "${!var}" =~ ^[A-Za-z0-9_-]+$ ]];
+        then
+            exit_with "Failed to build. Package $var '${!var}' contains invalid characters." 1
+        fi
+    done
+
+    # Pass over `$pkg_svc_run` to replace any `$pkg_name` placeholder tokens
+    # from prior pkg_svc_* variables that were set before the Plan was loaded.
+    if [[ -n "${pkg_svc_run+xxx}" ]]; then
+        pkg_svc_run="$(echo $pkg_svc_run | sed "s|@__pkg_name__@|$pkg_name|g")"
+    fi
+
+    if [[ -z "${pkg_version:-}" && "$(type -t pkg_version)" == "function" ]]; then
+        pkg_version="__pkg__version__unset__"
+    elif [[ -z "${pkg_version:-}" ]]; then
+        e="Failed to build. 'pkg_version' must be set or 'pkg_version()' function"
+        e="$e must be implemented and then invoking by calling 'update_pkg_version()'."
+        exit_with "$e" 1
+    fi
+
+    # If `$pkg_source` is used, default `$pkg_filename` to the basename of
+    # `$pkg_source` if it is not already set by the Plan.
+    if [[ -n "${pkg_source:-}" && -z "${pkg_filename+xxx}" ]]; then
+        pkg_filename="$(basename "$pkg_source")"
+    fi
+
+    # Set `$pkg_dirname` to the `$pkg_name` and `$pkg_version`, if it is not
+    # already set by the Plan.
+    if [[ -z "${pkg_dirname+xxx}" ]]; then
+        pkg_dirname="${pkg_name}-${pkg_version}"
+        _pkg_dirname_initially_unset=true
+    fi
+
+    # Set `$pkg_prefix` if not already set by the Plan.
+    if [[ -z "${pkg_prefix+xxx}" ]]; then
+        pkg_prefix=$HAB_PKG_PATH/${pkg_origin}/${pkg_name}/${pkg_version}/${pkg_release}
+    fi
+
+    # Set the cache path to be under the cache source root path
+    CACHE_PATH="$HAB_CACHE_SRC_PATH/$pkg_dirname"
+
+    # If `$pkg_source` is used, update the source path to build under the cache
+    # source path.
+    if [[ -n "${pkg_source:-}" ]]; then
+        SRC_PATH="$CACHE_PATH"
+    fi
+
+    if [[ -n "$HAB_OUTPUT_PATH" ]]; then
+        pkg_output_path="$HAB_OUTPUT_PATH"
+    else
+        pkg_output_path="$INITIAL_PWD/results"
+    fi
+
+    # Set $pkg_svc variables a second time, now that the Plan has been sourced and
+    # we have access to `$pkg_name`.
+    pkg_svc_path="$HAB_ROOT_PATH/svc/$pkg_name"
+    pkg_svc_data_path="$pkg_svc_path/data"
+    pkg_svc_files_path="$pkg_svc_path/files"
+    pkg_svc_var_path="$pkg_svc_path/var"
+    pkg_svc_config_path="$pkg_svc_path/config"
+    pkg_svc_static_path="$pkg_svc_path/static"
+
+    # Set the package artifact name
+    _artifact_ext="hart"
+    pkg_artifact="$HAB_CACHE_ARTIFACT_PATH/${pkg_origin}-${pkg_name}-${pkg_version}-${pkg_release}-${pkg_target}.${_artifact_ext}"
+
+    # Run `do_begin`
+    build_line "$_program setup"
+    do_begin
+
+    # Determine if we have all the commands we need to work
+    _find_system_commands
+
+    # Ensure that the origin key is available for package signing
+    _ensure_origin_key_present
+
+    _determine_hab_bin
+
+    _resolve_dependencies
+
+    # Set up runtime environment
+    _set_environment
+
+    mkdir -pv "$HAB_CACHE_SRC_PATH"
+
+    # Run any code after the environment is set but before the build starts
+    do_before
+
+    # Download the source
+    do_download
+
+    # Verify the source
+    do_verify
+
+    # Clean the cache
+    do_clean
+
+    # Unpack the source
+    do_unpack
+
+    # Set up the build environment
+    _build_environment
+
+    # Fix any libtool scripts in the source
+    _fix_libtool
+
+    # Make sure all required variables are set
+    _verify_vars
+
+    # Prepare the source
+    do_prepare_wrapper
+
+    # Build the source
+    do_build_wrapper
+
+    # Check the source
+    do_check_wrapper
+
+    # Install the source
+    do_install_wrapper
+
+    # Copy the configuration
+    do_build_config
+
+    # Copy the service management scripts
+    do_build_service
+
+    # Strip the binaries
+    do_strip
+
+    # Run any code after the package has finished building and installing, but
+    # before the artifact metadata is generated and the artifact is signed.
+    do_after
+
+    # Write the manifest
+    _build_manifest
+
+    # Render the linking and dependency files
+    _build_metadata
+
+    # Generate the artifact and write to artifact cache
+    _generate_artifact
+
+    # Copy produced artifact to a local relative directory
+    _prepare_build_outputs
+
+    # Cleanup
+    build_line "$_program cleanup"
+    do_end
+
+    # Print the results
+    build_line
+    build_line "Source Path: $SRC_PATH"
+    build_line "Installed Path: $pkg_prefix"
+    build_line "Artifact: $pkg_output_path/$(basename "$pkg_artifact")"
+    build_line "Build Report: $pkg_output_path/last_build.env"
+    build_line "SHA256 Checksum: $_pkg_sha256sum"
+    build_line "Blake2b Checksum: $_pkg_blake2bsum"
+
+    # Exit cleanly
+    build_line
+    build_line "I love it when a plan.sh comes together."
+    build_line
+    _on_exit  0
+
 fi
-# We check if the provided path has a `plan.sh` in it in either location. If
-# not, we'll quickly bail.
-if [[ ! -f "$PLAN_CONTEXT/plan.sh" ]]; then
-  if [[ -f "$PLAN_CONTEXT/habitat/plan.sh" ]]; then
-    # As the `plan.sh` is in a deeper subdirectory, we'll update the
-    # `$PLAN_CONTEXT` directory to be relative to the actual `plan.sh` file.
-    PLAN_CONTEXT="$PLAN_CONTEXT/habitat"
-  else
-    places="$PLAN_CONTEXT/plan.sh or $PLAN_CONTEXT/habitat/plan.sh"
-    exit_with "Plan file not found at $places" 42
-  fi
-fi
-
-# Change into the `$PLAN_CONTEXT` directory for proper resolution of relative
-# paths in `plan.sh`
-cd "$PLAN_CONTEXT"
-
-# Load the Plan
-build_line "Loading $PLAN_CONTEXT/plan.sh"
-if source "$PLAN_CONTEXT/plan.sh"; then
-  build_line "Plan loaded"
-else
-  ret=$?
-  exit_with "Failed to load Plan" $ret
-fi
-
-if [[ -n "$HAB_ORIGIN" ]]; then
-  pkg_origin="$HAB_ORIGIN"
-fi
-
-# Validate metadata
-build_line "Validating plan metadata"
-
-# Test for all required metadata keys
-required_variables=(
-  pkg_name
-  pkg_origin
-)
-for var in "${required_variables[@]}"
-do
-  if [[ -z "${!var}" ]] ; then
-    exit_with "Failed to build. '${var}' must be set." 1
-  fi
-done
-
-# Test to ensure package name contains only valid characters
-for var in pkg_name pkg_origin; do
-  if [[ ! "${!var}" =~ ^[A-Za-z0-9_-]+$ ]];
-  then
-    exit_with "Failed to build. Package $var '${!var}' contains invalid characters." 1
-  fi
-done
-
-# Pass over `$pkg_svc_run` to replace any `$pkg_name` placeholder tokens
-# from prior pkg_svc_* variables that were set before the Plan was loaded.
-if [[ -n "${pkg_svc_run+xxx}" ]]; then
-  pkg_svc_run="$(echo $pkg_svc_run | sed "s|@__pkg_name__@|$pkg_name|g")"
-fi
-
-if [[ -z "${pkg_version:-}" && "$(type -t pkg_version)" == "function" ]]; then
-  pkg_version="__pkg__version__unset__"
-elif [[ -z "${pkg_version:-}" ]]; then
-  e="Failed to build. 'pkg_version' must be set or 'pkg_version()' function"
-  e="$e must be implemented and then invoking by calling 'update_pkg_version()'."
-  exit_with "$e" 1
-fi
-
-# If `$pkg_source` is used, default `$pkg_filename` to the basename of
-# `$pkg_source` if it is not already set by the Plan.
-if [[ -n "${pkg_source:-}" && -z "${pkg_filename+xxx}" ]]; then
-  pkg_filename="$(basename "$pkg_source")"
-fi
-
-# Set `$pkg_dirname` to the `$pkg_name` and `$pkg_version`, if it is not
-# already set by the Plan.
-if [[ -z "${pkg_dirname+xxx}" ]]; then
-  pkg_dirname="${pkg_name}-${pkg_version}"
-  _pkg_dirname_initially_unset=true
-fi
-
-# Set `$pkg_prefix` if not already set by the Plan.
-if [[ -z "${pkg_prefix+xxx}" ]]; then
-  pkg_prefix=$HAB_PKG_PATH/${pkg_origin}/${pkg_name}/${pkg_version}/${pkg_release}
-fi
-
-# Set the cache path to be under the cache source root path
-CACHE_PATH="$HAB_CACHE_SRC_PATH/$pkg_dirname"
-
-# If `$pkg_source` is used, update the source path to build under the cache
-# source path.
-if [[ -n "${pkg_source:-}" ]]; then
-  SRC_PATH="$CACHE_PATH"
-fi
-
-if [[ -n "$HAB_OUTPUT_PATH" ]]; then
-  pkg_output_path="$HAB_OUTPUT_PATH"
-else
-  pkg_output_path="$INITIAL_PWD/results"
-fi
-
-# Set $pkg_svc variables a second time, now that the Plan has been sourced and
-# we have access to `$pkg_name`.
-pkg_svc_path="$HAB_ROOT_PATH/svc/$pkg_name"
-pkg_svc_data_path="$pkg_svc_path/data"
-pkg_svc_files_path="$pkg_svc_path/files"
-pkg_svc_var_path="$pkg_svc_path/var"
-pkg_svc_config_path="$pkg_svc_path/config"
-pkg_svc_static_path="$pkg_svc_path/static"
-
-# Set the package artifact name
-_artifact_ext="hart"
-pkg_artifact="$HAB_CACHE_ARTIFACT_PATH/${pkg_origin}-${pkg_name}-${pkg_version}-${pkg_release}-${pkg_target}.${_artifact_ext}"
-
-# Run `do_begin`
-build_line "$_program setup"
-do_begin
-
-# Write out a prebuild file so workers can have some metadata about failed builds
-_write_pre_build_file
-
-# Determine if we have all the commands we need to work
-_find_system_commands
-
-# Ensure that the origin key is available for package signing
-_ensure_origin_key_present
-
-_determine_hab_bin
-
-_resolve_dependencies
-
-# Set up runtime environment
-_set_environment
-
-mkdir -pv "$HAB_CACHE_SRC_PATH"
-
-# Run any code after the environment is set but before the build starts
-do_before
-
-# Download the source
-do_download
-
-# Verify the source
-do_verify
-
-# Clean the cache
-do_clean
-
-# Unpack the source
-do_unpack
-
-# Set up the build environment
-_build_environment
-
-# Fix any libtool scripts in the source
-_fix_libtool
-
-# Make sure all required variables are set
-_verify_vars
-
-# Prepare the source
-do_prepare_wrapper
-
-# Build the source
-do_build_wrapper
-
-# Check the source
-do_check_wrapper
-
-# Install the source
-do_install_wrapper
-
-# Copy the configuration
-do_build_config
-
-# Copy the service management scripts
-do_build_service
-
-# Strip the binaries
-do_strip
-
-# Run any code after the package has finished building and installing, but
-# before the artifact metadata is generated and the artifact is signed.
-do_after
-
-# Write the manifest
-_build_manifest
-
-# Render the linking and dependency files
-_build_metadata
-
-# Generate the artifact and write to artifact cache
-_generate_artifact
-
-# Copy produced artifact to a local relative directory
-_prepare_build_outputs
-
-# Cleanup
-build_line "$_program cleanup"
-do_end
-
-# Print the results
-build_line
-build_line "Source Path: $SRC_PATH"
-build_line "Installed Path: $pkg_prefix"
-build_line "Artifact: $pkg_output_path/$(basename "$pkg_artifact")"
-build_line "Build Report: $pkg_output_path/last_build.env"
-build_line "SHA256 Checksum: $_pkg_sha256sum"
-build_line "Blake2b Checksum: $_pkg_blake2bsum"
-
-# Exit cleanly
-build_line
-build_line "I love it when a plan.sh comes together."
-build_line
-_on_exit  0
